#ifndef CONTRIB_UCPORT_INCLUDE_PORT_STM8_IMPL_STM8_DEVICE_MOTOR_H_
#define CONTRIB_UCPORT_INCLUDE_PORT_STM8_IMPL_STM8_DEVICE_MOTOR_H_

#include <ioapi/device.h>

extern const device_descriptor_t g_stm8_device_motor;

#endif /* CONTRIB_UCPORT_INCLUDE_PORT_STM8_IMPL_STM8_DEVICE_MOTOR_H_ */
